name: Build Yocto

on:
  workflow_call:
    outputs:
      artifacts_url:
        description: "URL to retrieve build artifacts"
        value: ${{ jobs.create-output.outputs.url }}

env:
  CACHE_DIR: /efs/qli/meta-qcom
  KAS_REPO_REF_DIR: /efs/qli/meta-qcom/kas-mirrors
  KAS_CONTAINER: /efs/qli/meta-qcom/kas-mirrors/kas-container

jobs:
  kas-setup:
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, qcom-u2404, amd64-ssd]
    steps:
      - name: Update kas-container
        run: |
          LATEST=$(git ls-remote --tags --refs --sort="v:refname" https://github.com/siemens/kas | tail -n1 | sed 's/.*\///')
          wget -qO ${KAS_CONTAINER} https://raw.githubusercontent.com/siemens/kas/refs/tags/$LATEST/kas-container
          chmod +x ${KAS_CONTAINER}

      - name: Update kas mirrors
        run: |
          for r in $(find ${KAS_REPO_REF_DIR}/* -maxdepth 0 -type d); do
            echo "pre-fetch: $r"
            git -C $r fetch --prune origin '+refs/*:refs/*'
          done

      - uses: actions/checkout@v4

      - name: Run kas lock
        run: |
          ${KAS_CONTAINER} lock --update ci/base.yml:ci/qcom-distro.yml

      - uses: actions/upload-artifact@v4
        with:
          name: kas-lock
          path: ci/*.lock.yml

  yocto-run-checks:
    needs: kas-setup
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, qcom-u2404, amd64-ssd]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v6
        with:
          name: kas-lock
          path: ci/

      - name: Run yocto-check-layer
        run: |
          ci/kas-container-shell-helper.sh ci/yocto-check-layer.sh

      - name: Run Yocto patchreview
        run: |
          ci/kas-container-shell-helper.sh ci/yocto-patchreview.sh

  compile_warm_up:
    needs: [kas-setup, yocto-run-checks]
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, qcom-u2404, amd64-ssd]
    strategy:
      fail-fast: true
      matrix:
        machine:
          - rb3gen2-core-kit
          - qcom-armv8a
        distro:
          - name: poky-altcfg
            yamlfile: ""
          - name: qcom-distro
            yamlfile: ':ci/qcom-distro.yml'
          - name: qcom-distro-prop-image
            yamlfile: ':ci/qcom-distro-prop-image.yml'
          # kvm is compatible with all the compile warm up machines
          - name: qcom-distro-kvm
            yamlfile: ':ci/qcom-distro-kvm.yml'
          - name: qcom-distro-sota
            yamlfile: ':ci/qcom-distro-sota.yml'
        kernel:
          - type: default
            dirname: ""
            yamlfile: ""
    name: ${{ matrix.machine }}/${{ matrix.distro.name }}${{ matrix.kernel.dirname }}
    steps:
      - uses: actions/checkout@v4

      - name: Run kas build
        uses: ./.github/actions/compile
        with:
          machine: ${{matrix.machine}}
          distro_yaml: ${{matrix.distro.yamlfile}}
          distro_name: ${{matrix.distro.name}}
          kernel_yaml: ${{matrix.kernel.yamlfile}}
          kernel_dirname: ${{matrix.kernel.dirname}}
          cache_dir: ${CACHE_DIR}
          kas: ${KAS_CONTAINER}

  compile:
    needs: compile_warm_up
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, qcom-u2404, amd64-ssd]
    outputs:
      url: ${{ steps.compile_kas.outputs.url }}
    strategy:
      fail-fast: true
      matrix:
        machine:
          - iq-8275-evk
          - iq-9075-evk
          - kaanapali-mtp
          - qcm6490-idp
          - qcs615-ride
          - qcs8300-ride-sx
          - qcs9100-ride-sx
          - qcom-armv7a
          - rb1-core-kit
          - sm8750-mtp
        distro:
          - name: poky-altcfg
            yamlfile: ""
          - name: qcom-distro
            yamlfile: ':ci/qcom-distro.yml'
          - name: qcom-distro-prop-image
            yamlfile: ':ci/qcom-distro-prop-image.yml'
          - name: qcom-distro-sota
            yamlfile: ':ci/qcom-distro-sota.yml'
        kernel:
          - type: default
            dirname: ""
            yamlfile: ""
        include:
          # Additional builds for specific machines
          - machine: qcom-armv8a
            distro:
                name: qcom-distro
                yamlfile: ':ci/qcom-distro.yml'
            kernel:
                type: additional
                dirname: "+linux-yocto-dev"
                yamlfile: ":ci/linux-yocto-dev.yml"
          - machine: qcom-armv8a
            distro:
                name: qcom-distro
                yamlfile: ':ci/qcom-distro.yml'
            kernel:
                type: additional
                dirname: "+linux-yocto-lts"
                yamlfile: ":ci/linux-yocto-lts.yml"
          # include kvm compatible machines for the builds
          - machine: qcs9100-ride-sx
            distro:
                name: qcom-distro-kvm
                yamlfile: ':ci/qcom-distro-kvm.yml'
            kernel:
                type: default
                dirname: ""
                yamlfile: ""
        exclude:
          # Incompatible builds
          - machine: qcom-armv7a
            distro:
                name: qcom-distro-prop-image
    name: ${{ matrix.machine }}/${{ matrix.distro.name }}${{ matrix.kernel.dirname }}
    steps:
      - uses: actions/checkout@v4

      - name: Run kas build
        uses: ./.github/actions/compile
        id: compile_kas
        with:
          machine: ${{matrix.machine}}
          distro_yaml: ${{matrix.distro.yamlfile}}
          distro_name: ${{matrix.distro.name}}
          kernel_yaml: ${{matrix.kernel.yamlfile}}
          kernel_dirname: ${{matrix.kernel.dirname}}
          cache_dir: ${CACHE_DIR}
          kas: ${KAS_CONTAINER}

  publish_summary:
    needs: compile
    runs-on: [self-hosted, qcom-u2404, amd64-ssd]
    steps:
      - name: 'Download build URLs'
        uses: actions/download-artifact@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: build-url*
          path: urlfiles
          merge-multiple: true

      - name: "Print output"
        shell: python
        id: print-output
        run: |
          import os
          ftable = {}
          oslist = set()
          machinelist = set()
          for fname in os.listdir("./urlfiles"):
              if fname.startswith("build-url"):
                  b, m, o = fname.split("_", 2)
                  oslist.add(o)
                  machinelist.add(m)
                  url = ""
                  with open(f"./urlfiles/{fname}", "r") as urlfile:
                      url = urlfile.read()
                  if not o in ftable:
                      ftable.update({o:{m: url}})
                  else:
                      ftable[o].update({m: url})

          table_str = "| |"

          for m in sorted(machinelist):
              table_str += f" {m} |"

          table_str += "\n|"
          for i in range(len(machinelist) + 1):
              table_str += " ---- |"

          table_str += "\n"

          for o in sorted(ftable.keys()):
              table_str += f"| {o} |"
              for m in sorted(machinelist):
                  url = ftable[o].get(m)
                  if url:
                      url = url.strip()
                      table_str += f" [Files]({url}/{o}/{m}/) |"
                  else:
                      table_str += " |"
              table_str += "\n"
          summary_file_name = os.environ.get("GITHUB_STEP_SUMMARY")
          if summary_file_name:
              with open(summary_file_name, "a") as summaryfile:
                  summaryfile.write("## Download URLs\n")
                  summaryfile.write(table_str)
          print(table_str)
